[package]
name = "peter-python"
version = "0.1.0"
authors = ["Fenhl <fenhl@fenhl.net>"]
edition = "2018"

[lib]
name = "peter"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies.peter-ipc]
path = "../peter-ipc"

[dependencies.pyo3]
version = "0.13"
features = ["extension-module"]

[dependencies.serenity]
version = "0.10"
default-features = false
features = ["model", "utils"]
