[package]
name = "peter-cli"
version = "0.1.0"
authors = ["Fenhl <fenhl@fenhl.net>"]
edition = "2018"

[[bin]]
name = "peter"
path = "src/main.rs"

[dependencies]
async-std = "1"
chrono = "0"
parking_lot = "0.9" # because serenity still uses 0.9
serde_json = "1"
serenity = "0.8"
typemap = "0"

[dependencies.peter]
path = "../peter"
