[package]
name = "peter-cli"
version = "0.1.0"
authors = ["Fenhl <fenhl@fenhl.net>"]
edition = "2021"

[[bin]]
name = "peter"
path = "src/main.rs"

[dependencies]
async-trait = "0.1"
chrono = "0.4"
itertools = "0.10"
serde_json = "1"
serenity = "0.10"

[dependencies.peter]
path = "../peter"

[dependencies.serenity-utils]
git = "https://github.com/fenhl/serenity-utils" #TODO publish to crates.io?
branch = "main"

[dependencies.tokio]
version = "1"
features = ["macros", "rt-multi-thread"]
