[package]
name = "peter"
version = "0.1.0"
authors = ["Fenhl <fenhl@fenhl.net>"]
edition = "2021"

[dependencies]
chrono = "0.4"
futures = "0.3"
itertools = "0.10"
num-traits = "0.2"
once_cell = "1"
rand = "0.8"
regex = "1"
serde_json = "1"
serenity = "0.11"
thiserror = "1"

[dependencies.discord-message-parser]
git = "https://github.com/fenhl/discord-message-parser"

[dependencies.quantum-werewolf]
git = "https://github.com/dasgefolge/quantum-werewolf"
branch = "main"

[dependencies.serde]
version = "1"
features = ["derive"]

[dependencies.serenity-utils]
git = "https://github.com/fenhl/serenity-utils" #TODO publish to crates.io?
branch = "main"

[dependencies.sqlx]
version = "0.6"
features = ["json", "macros", "postgres", "runtime-tokio-rustls"]

[dependencies.tokio]
version = "1"
features = ["process", "time"]

[dependencies.twitch_helix]
git = "https://github.com/fenhl/rust-twitch-helix" #TODO publish to crates.io
branch = "main"

[dependencies.wheel]
git = "https://github.com/fenhl/wheel"
branch = "main"
